### PR TITLE
Completed tag Servlet

### PR DESCRIPTION
**Pull request by xuau34**
# Learned
* `git diff filename` to see what I've changed in this file
*  Using jQuery to create an html element - `$(document.createElement('tag'))` is way more faster
  * reference - https://stackoverflow.com/questions/268490/jquery-document-createelement-equivalent
* The reason that the tutorial code for including bootstrap contains `integral` and `Crossorigin`
  * reference - https://stackoverflow.com/questions/32039568/what-are-the-integrity-and-crossorigin-attributes
  * **Integrity attribute** is to allow the browser to check the file source to ensure that the code is never loaded if the source has been manipulated.
  * **Crossorigin** attribute is present when a request is loaded using 'CORS' which is now a requirement of SRI checking when not loaded from the 'same-origin'.
 * The datastore in appengine uses default incremental key.
 * There's a way to use specific string to generate UUID. by Bytes & MD5. Some stakeoverflow says it's broken. Haven't known the reason yet.
# Tag
* tag, String, the name of this tag
* userId, String, the owner
* eventDateTime, long, the latest time of the event that contain this tag
* timestamp, long, the time this tag is created
# TagServlet
Require users log in first, which has been filter by `LoginFilter.java`
There's two url patterns for use.
### GET
It will prints out user's incoming tags in JSON.
```
[{
"userId":"185804764220139124118",
"tag":"abc",
"eventDateTime":1563083515969,
"timestamp":1563083517640
},{
"userId":"185804764220139124118",
"tag":"abcd",
"eventDateTime":1563083601937,
"timestamp":1563083606250
}]
```
### POST
Required parameters -
* `method` - `update` or `delete`, indicates which function this form needs
### `update`
Required parameters -
* `tag` - String, the tag's name
* `eventDateTime` - String, the ISO version of the Date class in js
Return in JSON - tag or error message
tag - 
```
{
"userId":"185804764220139124118",
"tag":"abc",
"eventDateTime":1563083515969,
"timestamp":1563083517640
}
```
### `delete`
Required parameters -
* `tag` - String, the tag's name
Return in JSON - success or error message
```
{"status":"Success"}
```

### CODE REVIEW

**Comment by xuau34** [comment]
Because `DateTime is not a supported property type.`, the Tag class will remain using long to store `eventDateTime`.
I'll search more about this later on

**Comment by xuau34** [comment]
Added a option in `CalendarServlet` so that we can use `?tag=*tag*` to require those events that have this tag.

**Review by zhiyichin — APPROVED** [review]
Looks great!

**Review by zhiyichin — COMMENTED** [review]
Looks great!

**Pull request merged**
